### ISSUE TITLE
Does not work with Tikzexternalise

### ISSUE THREAD

**Issue by krishnakumarg1984** [fabianlipp/luatodonotes#5]
Raises errors with Tikz externalisation.

Note that the todonotes package had the same issue. But there is a fix for it in this stackexchange post
https://tex.stackexchange.com/questions/42486/todonotes-and-tikzexternalize/115095

Can you please provide a similar workaround for luatodonotes to fix these errors.

**Comment by fabianlipp** [comment]
A similar fix should work for luatodonotes. Can you send me a small example document (MWE) to test my changes?

**Comment by krishnakumarg1984** [comment]
Thank you for your reply. It does not work for me.

I am using the template here at https://github.com/holgern/TUB_PhDThesisTemplate.git . This is a working template if you simply download the repo (or clone it)

Just add the following lines before \begin{document}
\makeatletter
\renewcommand{\todo}[2][]{\tikzexternaldisable\@todo[#1]{#2}\tikzexternalenable}
\makeatother

and use \todo{something} in any of the chapters. 

The following error is obtained.
>1_introduction/introduction.tex|89 error|  I can't write on file `./1_introduction/TikzPictures/main-figure9.md5' <to be read again>  \relax  \item c
1_introduction/introduction.tex|89 error|  Emergency stop <to be read again>  \relax  \item c


With todonotes package this problem does not occur.

**Comment by fabianlipp** [comment]
The template does not work on my system. Can you send my a small file using tikz externalization and a todo note?
https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-example-what-is-that

**Comment by krishnakumarg1984** [comment]
Yes. I shall try. Meanwhile, see here. Someone else had exactly the same problem much before me. The question went unanswered.


https://tex.stackexchange.com/questions/236168/luatodonotes-and-tikz-externalization-wont-mix

**Comment by fabianlipp** [comment]
Thanks for the link. I will try the example posted there. That should be fine

**Comment by fabianlipp** [comment]
Can you try if the version in branch `tikzexternalize` (966d34f2f165991c444ef3d91f9be2463df35800) solves your prolem?

**Comment by krishnakumarg1984** [comment]
Yes. Certainly.  Is it sufficient to simply clone this branch and place it in $PATH such that this branch comes before the standard texlive tree ?

**Comment by fabianlipp** [comment]
Run `latex luatodonotes.ins` to generate the package files and copy the listed files into your TEXMF tree.
But TeX doesn't care for the usual $PATH variable. In TexLive you can use `kpsepath tex` to see in which directories TeX looks for packages. There are also variables to modify this path (depending on your TeX distribution. Don't forget to run `texhash`.

**Comment by krishnakumarg1984** [comment]
Hi Fabian,

I tried the fix.  First cloned the ```tikzexternalize``` branch, ran latex on it to generate the .sty file. Then moved all the requisite 5 files (.sty and .lua) to ```~/texmf/tex/lualatex``` and finally ran ```texhash ~/texmf```.  Upon compiling my ```main.tex``` I still get these same errors (concise summary pretty printed by ```pplatex``` parser):

>1_introduction/introduction.tex|89 error|  I can't write on file `./1_introduction/TikzPictures/main-figure9.md5' <to be read again>  \relax  \item c
1_introduction/introduction.tex|89 error|  Emergency stop <to be read again>  \relax  \item c

This problem does not exist with the standard ```todonotes``` package with the fixes below

```
\makeatletter
\renewcommand{\todo}[2][]{\tikzexternaldisable\@todo[#1]{#2}\tikzexternalenable}
\makeatother
```

Did you expect me to remove these lines with your latest attempted fix?

**Comment by fabianlipp** [comment]
> Did you expect me to remove these lines with your latest attempted fix?

Yes. This line is not needed for luatodonotes with my fix.

> Upon compiling my main.tex I still get these same errors (concise summary pretty printed by pplatex parser):
>    1_introduction/introduction.tex|89 error| I can't write on file `./1_introduction/TikzPictures/main-figure9.md5' \relax \item c
>    1_introduction/introduction.tex|89 error| Emergency stop \relax \item c

I'm not sure if this is related to luatodonotes. Seems like you have lots of tikzpictures in your document. Can you try to delete the already generated files `main-figure*.*` and try again?
Otherwise remove some figures from your document and try if it also fails with one figure.

**Comment by krishnakumarg1984** [comment]
yes. Removed the lines consisting of the temporary tikz externalise command.

I deleted all the generated files with ```rm main-figure*``` and also performed a thorough removal of all auxiliary files produced by the compiler. The same error persists. 

I am not sure if I want to go through my full thesis and comment out all figures. That will break a lot of things such as references to figures, sectioning, page breaking etc.

Clearly, there is a strong conflict with tikzexternalise. The package developer of todonotes also makes this conflict clear and known in the documentation pdf opened by running ```texdoc todonotes```. The suggested workaround is the same as what I have been using. 

On top of the existing conflicts, I think ```luatodonotes``` introduces something more that further clashes with tikzexternalise.

If it helps, I notice a weird behavior. Without ```luatodonotes```, the aux files of tikzexternalise such as ```main-figurex.md5``` and ```main-figurex.dpth``` were generated in the correct sub-directories that contained the original tikz source code.  With ```luatodonotes```, these aux files from tikzexternalise seem to be contaminating the project's root directory. 

This could be the meaning behind, 
1_introduction/introduction.tex|89 error|  I can't write on file `./1_introduction/TikzPictures/main-figure9.md5'

Something about ```luatodnotes``` takes away the write permissions of tikzexternalise into the sub-folder (in this case ./1_introduction/TikzPictures/), forcing it attempt to write the aux files in the project root.  I think ```luatodonotes``` is the culprit here, since this worked absolutely fine with and without the ordinary ```todonotes``` packages.  

It could even be a bug in the luatex engine, which really escalates things outside the purview of this package? I think TL2018 has a June release, which means the luatex developers might need to be notified  sooner than later.

**Comment by fabianlipp** [comment]
How did you compile the file using the todonotes package? Did you run `pdflatex` or `lualatex`? Usually both TeX engines should work when you don't use luatodonotes.

**Comment by krishnakumarg1984** [comment]
Hi Fabian,

My project uses ```luatex```. I also read the PDF documentation for your package wherein you clearly and unambiguously state that ```luatodonotes``` explicitly uses lua's placement algorithms and can only work with ```luatex```.

I specify ```luatex``` as the engine through the directive ```!% TEX program = lualatex``` in the first line of my ```main.tex```.  Furthermore, the detailed ```main.log``` also confirms that ```luatex``` is indeed the engine that runs.

I am interested in ```luatodonotes``` because the standard ```todonotes``` overruns the page margins in the top and bottom, even resulting in truncated todo boxes.  I am interested in the advertised capabilities of ```luatodonotes``` that can leverage the power of lua for smarter placement of these todo boxes.

Let me help you out a bit.  I can invite you to my thesis repo (with my content removed) on overleaf. You can try it out yourself. Does that work?

**Comment by fabianlipp** [comment]
> Let me help you out a bit. I can invite you to my thesis repo (with my content removed) on overleaf. You can try it out yourself. Does that work?

Yes, of course. Perhaps I can see the problem

**Comment by krishnakumarg1984** [comment]
Alright. A project capable of demonstrating the issue is now on https://www.overleaf.com/15438051nxwkpwqfckhq#/58536412/
It correctly typesets without errors and is at present using the basic ```todonotes``` package and the fixes for tikzexternalise. 
____________________________________________________________________________________________________________

Please then navigate to ```Preamble/custompreamble.tex```.

After ensuring that your latest bug-fix branch is in your TEXMF path, you may uncomment __line 6__ to include the ```luatodonotes``` package.  Immediately comment out __lines 10 - 18__ (to get rid of the standard ```todonotes``` and its workarounds for tikzexternalise from the [original TeX.SX answer](https://tex.stackexchange.com/questions/42486/todonotes-and-tikzexternalize/115095) )

**Comment by krishnakumarg1984** [comment]
Gentle nudge :)

**Comment by fabianlipp** [comment]
I just tried to compile the document. But the TUB documentclass doesn't work for me. So I cannot run it locally and it times out using luatodonotes on Overleaf (and I can't find out why). I tried to play around with it a bit and didn't get it running.

Again, debugging would be **much** easier if I am provided a MWE (that uses a standard documentclass like scrartcl). Or can you certify that the problem only occurs with the TUB documentclass?

**Comment by tom-anders** [comment]
The fix seems to work for me, will this be merged into master anytime soon?
